site_name: osuNoLimits Dev Wiki

nav:
  - Installation: index.md
  - Extending shiina: plugins.md

repo_url: https://github.com/osu-NoLimits/wiki/
edit_uri_template: 'blob/main/docs/{path}'

theme:
  name: material
  highlightjs: true
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
