site_name: osuNoLimits Dev Wiki

nav:
  - Home: index.md
  - Extending shiina: plugins.md

repo_url: https://github.com/osu-NoLimits/wiki/
edit_uri: 'blob/main/docs/'
edit_uri_template: 'blob/main/docs/{path}'

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust