site_name: osuNoLimits Dev Wiki

nav:
  - Installation: index.md
  - Extending shiina: plugins.md

repo_url: https://github.com/osu-NoLimits/wiki/
edit_uri: 'blob/main/docs/'
edit_uri_template: 'blob/main/docs/{path}'

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences